name: CD Pipeline

on: [push]

jobs:
  build-nix:
    env:
      IN_PIPELINE: true
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        type: [ubuntu-x64, ubuntu-x86, armv7, aarch64]
        include:
          - type: ubuntu-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            name: x86_64-linux-feroxagent
            path: target/x86_64-unknown-linux-musl/release/feroxagent
            pkg_config_path: /usr/lib/x86_64-linux-gnu/pkgconfig
          - type: ubuntu-x86
            os: ubuntu-latest
            target: i686-unknown-linux-musl
            name: x86-linux-feroxagent
            path: target/i686-unknown-linux-musl/release/feroxagent
            pkg_config_path: /usr/lib/i686-linux-gnu/pkgconfig
          - type: armv7
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            name: armv7-linux-feroxagent
            path: target/armv7-unknown-linux-gnueabihf/release/feroxagent
            pkg_config_path: /usr/lib/x86_64-linux-gnu/pkgconfig
          - type: aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: aarch64-linux-feroxagent
            path: target/aarch64-unknown-linux-gnu/release/feroxagent
            pkg_config_path: /usr/lib/x86_64-linux-gnu/pkgconfig
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
          toolchain: stable
      - name: Build tar.gz for homebrew installs
        if: matrix.type == 'ubuntu-x64'
        run: |
          tar czf ${{ matrix.name }}.tar.gz -C target/x86_64-unknown-linux-musl/release feroxagent
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}
      - uses: actions/upload-artifact@v4
        if: matrix.type == 'ubuntu-x64'
        with:
          name: ${{ matrix.name }}.tar.gz
          path: ${{ matrix.name }}.tar.gz

  build-debug:
    env:
      IN_PIPELINE: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          env
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libssl-dev pkg-config musl-tools
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Build the project
        env:
          PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
          OPENSSL_DIR: /usr/lib/ssl
        run: cargo build --target=x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux-debug-feroxagent
          path: target/x86_64-unknown-linux-musl/debug/feroxagent

  build-debug-windows:
    env:
      IN_PIPELINE: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Build the project
        run: cargo build --target=x86_64-pc-windows-msvc
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-windows-debug-feroxagent.exe
          path: target\x86_64-pc-windows-msvc\debug\feroxagent.exe

  build-macos:
    env:
      IN_PIPELINE: true
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: x86_64-apple-darwin
          args: "--locked --release"
          strip: true
          toolchain: stable
      - name: Build tar.gz for homebrew installs
        run: |
          tar czf x86_64-macos-feroxagent.tar.gz -C target/x86_64-apple-darwin/release feroxagent
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-macos-feroxagent
          path: target/x86_64-apple-darwin/release/feroxagent
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-macos-feroxagent.tar.gz
          path: x86_64-macos-feroxagent.tar.gz

  build-macos-aarch64:
    env:
      IN_PIPELINE: true
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: aarch64-apple-darwin
          args: "--locked --release"
          strip: true
          toolchain: stable
      - name: Build tar.gz for homebrew installs
        run: |
          tar czf aarch64-macos-feroxagent.tar.gz -C target/aarch64-apple-darwin/release feroxagent
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-macos-feroxagent
          path: target/aarch64-apple-darwin/release/feroxagent
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-macos-feroxagent.tar.gz
          path: aarch64-macos-feroxagent.tar.gz

  build-windows:
    env:
      IN_PIPELINE: true
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        type: [windows-x64, windows-x86]
        include:
          - type: windows-x64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            name: x86_64-windows-feroxagent.exe
            path: target\x86_64-pc-windows-msvc\release\feroxagent.exe
          - type: windows-x86
            os: windows-latest
            target: i686-pc-windows-msvc
            name: x86-windows-feroxagent.exe
            path: target\i686-pc-windows-msvc\release\feroxagent.exe
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target:  ${{ matrix.target }}
          args: "--locked --release"
          strip: true
          toolchain: stable
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}
